server:
    port: 80
cors:
    originPatterns: http://localhost:8080,http://localhost:3000,https://erudio.com.br,http://0.0.0.0:80,http://0.0.0.0:8080
file:
    upload-dir: /Temp/UploadDir    
security:
    jwt:
        token:
            secret-key: 53ccr37
            expire-length: 3600000   
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://rest-with-spring-boot-erudio.crelwwlz40i4.us-east-2.rds.amazonaws.com:3306/rest_with_spring_boot_erudio_?useTimezone=true&serverTimezone=UTC
        username: docker
        password: admin123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
    servelet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215mb
springdoc:
  pathsToMatch: 
    - /auth/**
    - /**/v1/**
  swagger-ui:
    use-root-path: true
